logging:
  level:
    org:
      springframework:
        beans: debug
        context: debug
      hibernate:
        type:
          descriptor:
            sql: trace
  
spring:
  datasource:
    url: jdbc:oracle:thin:@124.198.47.195:1521:XE
    username: jdeveloper43
    password: jdeveloper43
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate: 
        format_sql: true
    hibernate:
      ddl-auto: create
    #defer-datasource-initialization: true   
  # sql초기화  
  sql:
    init:
      mode: never
      schema-locations:
      #- classpath:user.ddl  
      #- classpath:board.ddl
      data-locations:
      #- classpath:user-insert.sql
      #- classpath:board-insert.sql
      continue-on-error: true
         
